include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: true
  errors:
    missing_return: error
    todo: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    must_be_immutable: ignore
