name: fake_object_generator
description: Build runner generator for fake_object test fakes.
version: 0.1.0
homepage: https://github.com/davidortegadiaz/fake_object
repository: https://github.com/davidortegadiaz/fake_object
issue_tracker: https://github.com/davidortegadiaz/fake_object/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  fake_object_annotation: ^0.1.0
  glob: ^2.1.2
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.9
  lint: ^2.3.0
