name: fake_object_annotation
description: Annotation package for fake_object code generation.
version: 0.1.0
homepage: https://github.com/davidortegadiaz/fake_object
repository: https://github.com/davidortegadiaz/fake_object
issue_tracker: https://github.com/davidortegadiaz/fake_object/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  lint: ^2.3.0
